local path = "chienan.config."
require(path .. "alpha")
require(path .. "bufferline")
require(path .. "gitsigns")
require(path .. "indent-blankline")
require(path .. "lualine")
require(path .. "neogit")
require(path .. "nvim-tree")
require(path .. "nvim-hop")
require(path .. "telescope")
require(path .. "treesitter")
